# Deep Dive into LLVM - Sphinx Configuration
# ===========================================

from datetime import datetime

# -- Project information -----------------------------------------------------

project = '浅入深出 LLVM'
author = 'noisystreet'
copyright = f'{datetime.now().year}, {author}'
html_title = '浅入深出 LLVM — 第一卷: LLVM 核心 | 第二卷: MLIR'

# The short X.Y version
version = '0.1'
# The full version, including alpha/beta/rc tags
release = '0.1'

# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinx.ext.extlinks',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.mermaid',
]

# -- Mermaid configuration ---------------------------------------------------

mermaid_output_format = 'raw'  # 在 RTD 上也能正常渲染

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'collapse_navigation': False,
    'navigation_depth': 3,
}
html_static_path = ['_static']
html_css_files = ['custom.css']

# -- Options for autosectionlabel --------------------------------------------

autosectionlabel_prefix_document = True

# -- Options for todo extension ----------------------------------------------

todo_include_todos = True

# -- Source file suffix ------------------------------------------------------

source_suffix = {
    '.rst': 'restructuredtext',
}

# -- Figure generation --------------------------------------------------------

figure_generators = ['source/figures/llvm_three_stage.py', 'source/figures/mlir_progressive_lowering.py']

def setup(app):
    """构建前自动生成 matplotlib 图表。"""
    app.connect('builder-inited', lambda app: generate_figures())

def generate_figures():
    import subprocess, sys, os
    script = os.path.join(os.path.dirname(__file__), '..', 'scripts', 'generate-figures.py')
    if os.path.exists(script):
        subprocess.run([sys.executable, script], cwd=os.path.dirname(script))

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'llvm': ('https://llvm.org/docs', None),
}
